#!/usr/bin/env python3
import os
import shutil
from os.path import expanduser, isdir
from time import strftime
import argparse

TIME = strftime("%d%m%Y%H%M%S")
DEST = expanduser("~") + '/.trash/'

known_rm_args = [
    '-f',
    '--force',
    '-i',
    '-I',
    '--interactive',
    '--one-file-system',
    '--no-preserve-root',
    '--preserve-root',
    '-r',
    '-R',
    '--recursive',
    '-d',
    '--dir',
    '-v',
    '--verbose',
]

ap = argparse.ArgumentParser(description='safe replacement for rm. rm+ moves files to ~/.trash')
ap.add_argument(*known_rm_args,  action='store_true')
args, files = ap.parse_known_args()

if not os.path.exists(DEST):
    os.makedirs(DEST)

for f in files:
    if not os.path.exists(f):
        print("cannot remove '%s': No such file or directory" % f)
    else:
        shutil.move(f, DEST + f + '.' + TIME)

